### ISSUE TITLE
How to run on Desktop (Ubuntu), I see an error 

### ISSUE THREAD

**Issue by foobnix** [1Coin-FinanceTracker/1CoinClient#113]
DesctopaCaused by: java.sql.SQLException: opening db: '/AppDatabase.db': Permission denied
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.JDBC.connect(JDBC.java:90)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at com.squareup.sqldelight.sqlite.driver.ThreadedConnectionManager.getConnection(JdbcSqliteDriver.kt:65)
	at com.squareup.sqldelight.sqlite.driver.JdbcSqliteDriver.getConnection(JdbcSqliteDriver.kt)
	at com.squareup.sqldelight.sqlite.driver.JdbcDriver.connectionAndClose(JdbcDriver.kt:96)
	at com.squareup.sqldelight.sqlite.driver.JdbcDriver.execute(JdbcDriver.kt:107)
	at com.squareup.sqldelight.db.SqlDriver$DefaultImpls.execute$default(SqlDriver.kt:52)
	at com.finance_tracker.finance_tracker.common.AppDatabaseImpl$Schema.create(AppDatabaseImpl.kt:84)
	at com.finance_tracker.finance_tracker.data.database.DriverFactory.createDriver(DriverFactory.kt:36)
	at com.finance_tracker.finance_tracker.data.database.di.CoreDatabaseModuleKt.provideAppDatabase(CoreDatabaseModule.kt:44)
	at com.finance_tracker.finance_tracker.data.database.di.CoreDatabaseModuleKt.access$provideAppDatabase(CoreDatabaseModule.kt:1)
	at com.finance_tracker.finance_tracker.data.database.di.CoreDatabaseModuleKt$coreDatabaseModule$1$invoke$$inlined$singleOf$default$2.invoke(SingleOf.kt:229)
	at com.finance_tracker.finance_tracker.data.database.di.CoreDatabaseModuleKt$coreDatabaseModule$1$invoke$$inlined$singleOf$default$2.invoke(SingleOf.kt:53)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:52)
	... 166 more

**Comment by foobnix** [comment]
![Screenshot from 2023-07-04 11-14-02](https://github.com/1Coin-FinanceTracker/1CoinClient/assets/432440/dae40cf2-4cf5-4d32-b984-688317b9bd78)

**Comment by VitalyPeryatin** [comment]
We don't support Desktop version for a while, because we don't have enough spare resources. But if you really need Desktop version of our application, we can do it by your help: 
- You can help to write an appropriate code for Desktop support
- You can support us by money and we will add Desktop support ourselves

Thank you for your attention. Sorry for lacking desktop support, but we're creating this app for free and can't to find enough spare resources. We're really appreciate your interest to our application! <3
